name: Openim-chat CI

on: 
  push:
  pull_request:

jobs:
  openim-chat:
    name: Test with go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment:
      name: openim

    strategy:
      matrix:
        go_version: ["1.20"]
        os: [ubuntu-latest]

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run go modules tidy
        run: |
          make tidy

      - name: Generate all necessary files, such as error code files
        run: |
          make generate

    #   - name: Check syntax and styling of go sources
    #     run: |
    #       set -e
    #       make lint

    #   - name: Run unit test and get test coverage
    #     run: |
    #       make cover

      - name: Build source code for host platform
        run: |
          # make build # skip build for now

      - name: Collect Test Coverage File
        uses: actions/upload-artifact@v1.0.0
        with:
          name: main-output
          path: _output/tmp/coverage.out

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # skip for now
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ env.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # skip for now
      - name: Build docker images for host arch and push images to registry
        run: |
          make docker-push